version: 2.1

jobs:
  co:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.17.
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod tidy
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - persist_to_workspace:
          root: .
          paths: [./* ]

  run-test:
    docker:
      - image: kohirens/git-tool-belt:0.7.0
        auth:
          username: ${DH_USER}
          password: ${DH_PASS}
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Unit test"
          command: |
            go test -v

workflows:
  pull-request:
    jobs:
      - co
      - runt-test:
          requires: [ co ]
          context: orb-publishing
