version: 2.1

orbs:
  vro: kohirens/version-release@2.2.0

parameters:
  ssh_finger:
    description: SSH fingerprint.
    type: string
    default: "73:9b:43:f6:57:91:be:f6:0f:a4:c1:05:40:37:ab:79"
  triggered_by_bot:
    description: Trigger publishing a release tag workflow.
    type: boolean
    default: false

jobs:
  co:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.mod" }}
      - run:
          name: Install Dependencies
          command: go mod tidy
      - save_cache:
          key: go-mod-v1-{{ checksum "go.mod" }}
          paths:
            - "/go/pkg/mod"
      - persist_to_workspace:
          root: .
          paths: [ ./* ]

  run-test:
    docker:
      - image: cimg/go:1.17
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.mod" }}
      - run:
          name: "Unit test"
          command: |
            go test -v

  publish-image:
    docker:
      - image: cimg/go:1.17
    steps:
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Build"
          command: |
            echo "Publishing tag '<< pipeline.git.tag >>'"
            export BUILD_VER="<< pipeline.git.tag >>"
            if [ -z "${BUILD_VER}" ]; then
                echo "cannot publish a Docker image, release tag was empty"
                exit 1
            fi
            docker build --build-arg "USER_NAME=circleci" --tag "kohirens/git-tool-belt:${BUILD_VER}" --file .docker/Dockerfile .
            docker login --username "${DH_USER}" --password "${DH_PASS}"
            docker push "kohirens/git-tool-belt:${BUILD_VER}"
            docker rmi "kohirens/git-tool-belt:${BUILD_VER}"

  publish-execs:
    docker:
      - image: kohirens/circleci-go:0.2.1
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Build"
          command: |
            echo "Publishing tag '<< pipeline.git.tag >>'"
            export BUILD_VER="<< pipeline.git.tag >>"
            if [ -z "${BUILD_VER}" ]; then
                echo "cannot publish executables, release tag was empty"
                exit 1
            fi
            go install
            export PATH="${PATH}:/root/go/bin"
            go generate
            chmod +x ./build-gh-artifacts.sh
            ./build-gh-artifacts.sh

filter-semantic-tag: &filter-semantic-tag
  tags:
    only: /^v?\d+\.\d+\.\d+$/
  branches:
    ignore: /.*/

workflows:
  pull-request:
    jobs:
      - co:
          filters:
            branches:
              ignore: /main|auto-update-changelog/
      - run-test:
          requires: [ co ]

  publish-changelog:
    when:
      and:
        - equal: [main, << pipeline.git.branch >>]
        - equal: [webhook, << pipeline.trigger_source >>]
    jobs:
      - vro/publish-changelog:
          context: orb-publishing
          ssh_finger: << pipeline.parameters.ssh_finger >>

  publish-release-tag:
    when:
      and:
        - equal: [main, << pipeline.git.branch >>]
    jobs:
      - vro/tag-and-release:
          context: orb-publishing

  on-tag-release:
    jobs:
      - publish-image:
          context: orb-publishing
          filters:
            <<: *filter-semantic-tag
      - publish-execs:
          context: orb-publishing
          filters:
            <<: *filter-semantic-tag
